# Created using YamlCreate.ps1 v1.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: JetBrains.CLion
PackageVersion: 212.5080.54
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://download.jetbrains.com/cpp/CLion-2021.2.1.exe
  InstallerSha256: c3c93ea4893a3b1ecf97959528d9089d5e9bb98a80957c5e871720f1655854f9
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

