# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Flicard.LocoSwap
PackageVersion: 1.6.1.0
PackageLocale: en-US
Publisher: Flicard
PackageName: LocoSwap
License: All RIghts Reserved
ShortDescription: Train Simulator utility to swap rolling stock of scenarios
ManifestType: defaultLocale
ManifestVersion: 1.6.0
